### PR TITLE
1st pass on setting run_spec.conf for open eval dataset

### PR DESCRIPTION
**Pull request by weiweiy**
Here is my 1st pass on run_spec.conf @drisspg  @msaroufim @jisaacso  Please sanity check. It is based on:
@drisspg's starting point https://gist.github.com/drisspg/92cad6df8d8ff43fee928a1df3203478
HELM's run_spec_lit: https://github.com/stanford-crfm/helm/blob/752a500f4b73a8ad31584437ccbd5647aa0bff3c/src/helm/benchmark/presentation/run_specs_lite.conf
HELM's bigbench lit: https://github.com/stanford-crfm/helm/blob/752a500f4b73a8ad31584437ccbd5647aa0bff3c/src/helm/benchmark/presentation/run_specs_lite.conf

### CODE REVIEW

**Comment by drisspg** [comment]
Output I got from running with 
`helm-run --conf-paths run_specs.conf --suite full -m 4 --num-threads 1`
https://gist.github.com/drisspg/d1af1f07ad7214d6aefca137f42ac453

**Comment by weiweiy** [comment]
@drisspg  Yeah, there was a typo in the model name... it is fixed now. Can you try again? Thanks

**Comment by drisspg** [comment]
there is another typo

```
entries: [
    #bigbench
    # 1. auto_debugging: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/auto_debugging
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=auto_debugging,subtask=", priority: 1}

    # 3. code_line_description: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/code_line_description
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=code_line_description,subtask=", priority: 1}

    # 4. conceptual_combinations: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/conceptual_combinations
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conceptual_combinations,subtask=contradictions", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conceptual_combinations,subtask=emergent_properties", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conceptual_combinations,subtask=fanciful_fictional_combinations", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conceptual_combinations,subtask=homonyms", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conceptual_combinations,subtask=invented_words", priority: 1}

    # 5. conlang_translation: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/conlang_translation
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=adna_from", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=adna_to", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=atikampe_from", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=atikampe_to", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=gornam_from", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=gornam_to", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=holuan_from", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=holuan_to", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=mkafala_from", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=mkafala_to", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=postpositive_english_from", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=postpositive_english_to", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=unapuri_from", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=unapuri_to", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=vaomi_from", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=conlang_translation,subtask=vaomi_to", priority: 1}

    # 6. emoji_movie: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/emoji_movie
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=emoji_movie,subtask=", priority: 1}

    # 7. formal_fallacies_syllogisms_negation: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/formal_fallacies_syllogisms_negation
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=formal_fallacies_syllogisms_negation,subtask=", priority: 1}

    # 8. hindu_knowledge: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/hindu_knowledge
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=hindu_knowledge,subtask=", priority: 1}

    # 9. known_unknowns: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/known_unknowns
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=known_unknowns,subtask=", priority: 1}

    # 10. language_identification: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/language_identification
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=language_identification,subtask=", priority: 1}

    # 11. linguistics_puzzles: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/linguistics_puzzles
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=linguistics_puzzles,subtask=", priority: 1}

    # 12. logic_grid_puzzle: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/logic_grid_puzzle
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=logic_grid_puzzle,subtask=", priority: 1}

    # 13. logical_deduction: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/logical_deduction
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=logical_deduction,subtask=three_objects", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=logical_deduction,subtask=five_objects", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=logical_deduction,subtask=seven_objects", priority: 1}

    # 14. misconceptions_russian: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/misconceptions_russian
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=misconceptions_russian,subtask=", priority: 1}

    # 15. novel_concepts: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/novel_concepts
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=novel_concepts,subtask=", priority: 1}

    # 16. operators: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/operators
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=operators,subtask=", priority: 1}

    # 17. parsinlu_reading_comprehension: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/parsinlu_reading_comprehension
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=parsinlu_reading_comprehension,subtask=", priority: 1}

    # 18. play_dialog_same_or_different: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/play_dialog_same_or_different
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=play_dialog_same_or_different,subtask=", priority: 1}

    # 19. repeat_copy_logic: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/repeat_copy_logic
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=repeat_copy_logic,subtask=", priority: 1}

    # 20. strange_stories: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/strange_stories
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=strange_stories,subtask=boolean", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=strange_stories,subtask=multiple_choice", priority: 1}

    # 21. strategyqa: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/strategyqa
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=strategyqa,subtask=", priority: 1}

    # 22. symbol_interpretation: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/symbol_interpretation
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=symbol_interpretation,subtask=adversarial", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=symbol_interpretation,subtask=emoji_agnostic", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=symbol_interpretation,subtask=name_agnostic", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=symbol_interpretation,subtask=plain", priority: 1}
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=symbol_interpretation,subtask=tricky", priority: 1}

    # 23. vitaminc_fact_verification: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/vitaminc_fact_verification
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=vitaminc_fact_verification,subtask=", priority: 1}

    # 24. winowhy: https://github.com/google/big-bench/tree/main/bigbench/benchmark_tasks/winowhy
    {description: "big_bench:model=neurips/local,max_train_instances=big_bench_few_shot_setting,task=winowhy,subtask=", priority: 1}

    #mmlu
    {description: "mmlu:model=neurips/local,subject=abstract_algebra,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=anatomy,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=college_chemistry,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=computer_security,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=econometrics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=global_facts,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=jurisprudence,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=philosophy,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=professional_medicine,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=us_foreign_policy,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=astronomy,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=business_ethics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=clinical_knowledge,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=college_biology,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=college_computer_science,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=college_mathematics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=college_medicine,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=college_physics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=electrical_engineering,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=formal_logic,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_biology,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_chemistry,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_computer_science,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_european_history,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_geography,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_government_and_politics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_macroeconomics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_mathematics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_microeconomics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_physics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_psychology,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_statistics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_us_history,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=high_school_world_history,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=human_aging,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=human_sexuality,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=international_law,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=logical_fallacies,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=machine_learning,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=management,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=marketing,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=medical_genetics,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=miscellaneous,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=moral_disputes,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=moral_scenarios,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=nutrition,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=prehistory,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=professional_accounting,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=professional_law,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=professional_psychology,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=public_relations,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=security_studies,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=sociology,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=virology,data_augmentation=canonical", priority: 2}
    {description: "mmlu:model=neurips/local,subject=world_religions,data_augmentation=canonical", priority: 2}

    #truthful QA
    {description: "truthful_qa:task=mc_single,model=neurips/local", priority: 1},

    #CNN/daily mail
    {description: "summarization_cnndm:model=neurips/local", priority: 1},
    #GSM
    {description: "gsm:model=neurips/local", priority: 1}
    #BBQ
    {description: "bbq:subject=all,model=neurips/local", priority: 1},

]
```

**Comment by timothylimyl** [comment]
hmm, what are the updates on this?  I saw that the discord leaderboard bot is up, I guess we can align the helm conf file for both open evaluation locally and on discord.

The faster this is confirmed, the better as users can evaluate locally and not use up the discord bot resources. ping @drisspg

**Review by msaroufim — APPROVED** [review]

**Pull request merged**
